#!/usr/bin/env bash
set -ex

for notebook in /code/Workshop-1_SimulatedAnalysis/solutions/*.ipynb; do
    jupyter nbconvert --to notebook --execute "$notebook" --inplace
done

for notebook in /code/Workshop-2_NonsenseCorrelations/solutions/*.ipynb; do
    jupyter nbconvert --to notebook --execute "$notebook" --inplace
done

for notebook in /code/Workshop-2_NonsenseCorrelations/Workshop-2_minis/*/*solutions.ipynb; do
    jupyter nbconvert --to notebook --execute "$notebook" --inplace
done